### PR TITLE
Update streamer.py

### PR DESCRIPTION
**Pull request by Quenos**
Fixing issue #100

## Related issue(s)
Fixes ...

## Pre-merge checklist
- [ ] Passing tests
- [ ] New tests added (if applicable)

### CODE REVIEW

**Comment by Quenos** [comment]
Why is this failing?

**Comment by Graeme22** [comment]
It looks like here

```python
channel = next((k for k, v in self._channels.items() if v == message['channel']), None)

self._subscription_state[channel]...
```

It's complaining that if the iterator is exhausted, the `_subscription_state` dict will be accessed with `None` as a key which will fail. You can omit the second argument, `None`, from the `next` function; that way, it'll raise an exception if the iterator reaches the end instead of passing `None` to the dict.

Alternatively, you could make channel a dict mapping int to the event type instead of the other way around.

**Comment by Quenos** [comment]
Apparently it broke something else now

**Comment by Graeme22** [comment]
Nope it's working well!

**Pull request merged**
