### PR TITLE
add more instruments

### PR DESCRIPTION
**Pull request by Graeme22**
- add more instruments; just missing option chains
- docs

### CODE REVIEW

**Comment by peter-oroszvari** [comment]
Option chains is the last missing endpoint?

**Comment by Graeme22** [comment]
Yes, but I'm trying to figure out how I want to structure it, there's a couple different ways:

- a function that returns a list of options
- a class wrapping different expirations that uses the nested chain

**Comment by Graeme22** [comment]
Ah also, there's nothing for orders yet, because that depends on the instrument implementation.

**Comment by peter-oroszvari** [comment]
The second option (nested chain) sounds better...

**Pull request merged**
