### PR TITLE
add candle to streamer

### PR DESCRIPTION
**Pull request by Graeme22**
watchlists:
- add/remove symbols
- update existing watchlist

streamer:
- add candle event
- small fixes
- candle subscribe/unsubscribe
- candle oneshot

### CODE REVIEW

**Comment by pingzh** [comment]
thanks a lot

**Comment by pingzh** [comment]
@Graeme22 when do you usually publish a new release?

**Comment by Graeme22** [comment]
> @Graeme22 when do you usually publish a new release?

There's no regular schedule, the next one is a really big one but we're pretty close, I'd say within a week or two

**Comment by pingzh** [comment]
thanks @Graeme22 is this included in your 5 alpha release?

**Comment by Graeme22** [comment]
> thanks @Graeme22 is this included in your 5 alpha release?

Yes! However the official one should be coming shortly.

**Pull request merged**
